@extends('layouts.app')

@section('title', 'Dashboard')
@section('page-title', 'Command center')

@section('content')
<section class="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-10 text-white shadow-2xl shadow-slate-950/20 sm:px-10 lg:px-12 lg:py-14">
    <div class="absolute -right-24 -top-24 size-80 rounded-full bg-indigo-500/25 blur-3xl"></div><div class="absolute -bottom-28 left-1/3 size-72 rounded-full bg-sky-400/15 blur-3xl"></div>
    <div class="relative grid gap-9 lg:grid-cols-[1.35fr_.65fr] lg:items-end"><div><p class="text-xs font-bold uppercase tracking-[.24em] text-indigo-300">TaskFlow command center</p><h2 class="mt-5 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">Keep every project moving forward.</h2><p class="mt-5 max-w-xl text-base leading-7 text-slate-300">A single view of delivery health, team workload, and the work that needs attention first.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('tasks.index') }}" class="rounded-xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-950/40 transition hover:bg-indigo-400">Open task workspace</a><a href="{{ route('projects.index') }}" class="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/10">View projects</a></div></div><div class="rounded-2xl border border-white/10 bg-white/10 p-5 backdrop-blur"><p class="text-xs font-semibold uppercase tracking-widest text-slate-300">Today’s focus</p><p class="mt-4 text-5xl font-semibold">{{ $overdue }}</p><p class="mt-1 text-sm text-slate-300">overdue tasks need a decision</p><div class="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-amber-400" style="width: {{ $totalTasks ? min(100, ($overdue / $totalTasks) * 100) : 0 }}%"></div></div></div></div>
</section>

<section class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Active projects'=>$activeProjects,'Visible tasks'=>$totalTasks,'In progress'=>$inProgress,'Completed today'=>$completedToday] as $label=>$value)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-widest text-slate-400">{{ $label }}</p><p class="mt-4 text-4xl font-semibold tracking-tight text-slate-950">{{ $value }}</p><div class="mt-4 h-1.5 rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" style="width: {{ $totalTasks ? min(100, ($value / $totalTasks) * 100) : 0 }}%"></div></div></article>@endforeach</section>

<section class="mt-9 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-indigo-600">Priority queue</p><h3 class="mt-2 text-xl font-semibold text-slate-950">My tasks</h3></div><a href="{{ route('tasks.index') }}" class="text-sm font-semibold text-indigo-700 hover:text-indigo-500">All tasks →</a></div><div class="mt-6 space-y-3">@forelse($myTasks as $task)<a href="{{ route('tasks.show',$task) }}" class="group flex items-center gap-4 rounded-2xl border border-slate-100 p-4 transition hover:border-indigo-200 hover:bg-indigo-50/40"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-bold text-slate-600 group-hover:bg-indigo-100 group-hover:text-indigo-700">{{ $task->priority->value[0] }}</span><div class="min-w-0 flex-1"><p class="truncate font-semibold text-slate-900">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $task->number }} · {{ $task->project->name }}</p></div><div class="text-right text-xs text-slate-500"><p class="font-semibold text-slate-700">{{ ucfirst(str_replace('_',' ',$task->status->value)) }}</p><p class="mt-1">{{ $task->due_at?->format('M j') ?? 'No due date' }}</p></div></a>@empty<p class="rounded-2xl bg-slate-50 px-5 py-10 text-center text-sm text-slate-500">No assigned tasks right now.</p>@endforelse</div></article><article class="rounded-3xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-900/10 sm:p-7"><p class="text-xs font-bold uppercase tracking-widest text-indigo-300">Workflow health</p><h3 class="mt-2 text-xl font-semibold">Status distribution</h3><div class="mt-7 space-y-5">@foreach(['Todo'=>$todo,'In progress'=>$inProgress,'Review'=>$review,'Archived projects'=>$archivedProjects] as $label=>$value)<div><div class="flex justify-between text-sm"><span class="text-slate-300">{{ $label }}</span><span class="font-semibold">{{ $value }}</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-indigo-400" style="width: {{ $totalTasks ? min(100, ($value / $totalTasks) * 100) : 0 }}%"></div></div></div>@endforeach</div><a href="{{ route('activity.index') }}" class="mt-8 block rounded-xl border border-white/15 px-4 py-3 text-center text-sm font-semibold text-white transition hover:bg-white/10">Review activity feed</a></article></section>

<section class="mt-9"><livewire:tasks.quick-task-create /></section>

<section class="mt-9 grid gap-6 lg:grid-cols-2"><article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-violet-600">Team timeline</p><h3 class="mt-2 text-xl font-semibold text-slate-950">Recent activity</h3></div><a href="{{ route('activity.index') }}" class="text-sm font-semibold text-indigo-700">See all</a></div><div class="mt-6 space-y-5">@forelse($recentActivity as $activity)<div class="flex gap-4"><span class="mt-1.5 size-2 shrink-0 rounded-full bg-indigo-500"></span><div><p class="font-medium text-slate-900">{{ \Modules\Activity\Support\ActivityDisplay::label($activity) }}</p>@if($summary=\Modules\Activity\Support\ActivityDisplay::summary($activity))<p class="mt-1 text-sm text-slate-500">{{ $summary }}</p>@endif<p class="mt-1 text-xs text-slate-400">{{ $activity->causer?->name ?: 'System' }} · {{ $activity->created_at->diffForHumans() }}</p></div></div>@empty<p class="text-sm text-slate-500">No recent activity in your permitted workspace.</p>@endforelse</div></article><article class="rounded-3xl border border-slate-200 bg-gradient-to-br from-indigo-50 to-sky-50 p-6 shadow-sm sm:p-7"><p class="text-xs font-bold uppercase tracking-widest text-indigo-600">Workspace actions</p><h3 class="mt-2 text-xl font-semibold text-slate-950">Keep the momentum.</h3><p class="mt-3 max-w-md text-sm leading-6 text-slate-600">Use the project and task workspaces to plan, assign, and follow up on delivery work.</p><div class="mt-7 grid gap-3 sm:grid-cols-2"><a href="{{ route('projects.create') }}" class="rounded-2xl bg-white p-4 text-sm font-semibold text-slate-900 shadow-sm transition hover:-translate-y-0.5">Create project <span class="mt-2 block text-xs font-medium text-slate-500">Start a new initiative</span></a><a href="{{ route('tasks.index') }}" class="rounded-2xl bg-indigo-600 p-4 text-sm font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-indigo-500">Review tasks <span class="mt-2 block text-xs font-medium text-indigo-100">Filter visible work</span></a></div></article></section>
@include('dashboard::_platform')
@include('dashboard::_workload')
@endsection
